#include "configuration_help.h"

const char configHelpText[] =
    "\r\n"
    "emon32 information and configuration commands\r\n\r\n"
    " - ?           : show this text again\r\n"
    " - a<n>        : set the assumed RMS voltage as integer\r\n"
    " - b           : backup to serial\r\n"
    " - c<n>        : log to serial output. n = 0: OFF, n = 1: ON, n = 2: "
    "verbose\r\n"
    " - d<x.x>      : data log period (s)\r\n"
    " - e           : enter bootloader\r\n"
    " - f<n>        : line frequency (Hz)\r\n"
    " - g<n>        : set network group (default = 210)\r\n"
    " - h           : safe power off countdown (will not remove power)\r\n"
    " - i<x> <m> <i.i> : Amplitude and phase calibration\r\n"
    "   - x         : channel (1-3 -> V; 4... -> CT)\r\n"
    "   - m         : mode select. m = a: amplitude, m = p: phase\r\n"
    "   - i.i       : actual voltage or current (amplitude only)\r\n"
    " - j<n>        : JSON serial format. n = 0: OFF, n = 1: ON\r\n"
    " - k<x> <a> <y.y> <z.z> v1 v2 : Configure an analog input\r\n"
    "   - x:        : channel (1-3 -> V; 4... -> CT)\r\n"
    "   - a:        : channel active. a = 0: DISABLED, a = 1: ENABLED\r\n"
    "   - y.y       : V/CT calibration constant\r\n"
    "   - z.z       : V/CT phase calibration value\r\n"
    "   - v1        : voltage 1 (for CT only)\r\n"
    "   - v2        : voltage 2 (for CT only, optional)\r\n"
    " - l           : list settings\r\n"
    " - ls          : list saved settings\r\n"
    " - lh          : list settings and accumulators (human readable)\r\n"
    " - lhs         : list saved settings and accumulators (human "
    "readable)\r\n"
    " - m<v> <w> <x> <y> <z> : Configure OPA1-3 for OneWire or Pulse\r\n"
    "   - v : OPA index. [1-3]\r\n"
    "   - w : OPA active. w = 0: DISABLED, w = 1: ENABLED\r\n"
    "   - x : function select. x = [b,f,r]: pulse, x = o: OneWire, x = a: "
    "analog\r\n"
    "   - y : pull-up, only for pulse. y = 0: OFF, y = 1: ON\r\n"
    "   - z : minimum time between pulses (ms), only for "
    "pulse.\r\n"
    " - n<n>        : set node ID [1..60]\r\n"
    " - o<x>        : configure OneWire addressing\r\n"
    "   - x = ca  : clear all saved OneWire addresses\r\n"
    "   - x = c<n>: clear saved address for channel n\r\n"
    "   - x = f   : reset and find OneWire devices\r\n"
    "   - x = h   : hold found addresses (overrides manually set values)\r\n"
    "   - x = l   : list current addresses\r\n"
    "   - x = n   : list all saved addresses\r\n"
    "   - x = r <a> <b> : remap found sensor <a> to index <b>\r\n"
    "   - x = <n> : move address to index <n>\r\n"
    " - p<n>        : set the RF power level\r\n"
    " - q           : reset system (requires confirmation)\r\n"
    " - r           : restore defaults\r\n"
    " - rs          : restore saved settings from NVM\r\n"
    " - s           : save settings to NVM\r\n"
    " - t           : trigger report on next cycle\r\n"
    " - u           : store current accumulator values to NVM\r\n"
    " - v           : firmware and board information\r\n"
    " - w<n>        : RF active. n = 0: OFF, n = 1: ON\r\n"
    " - x<n>        : 433 MHz compatibility. n = 0: 433.92 MHz, n = 1: "
    "433.00 MHz\r\n"
    " - ye<n> <m>   : set energy accumulator n to m Wh\r\n"
    " - yp<n> <m>   : set pulse accumulator n to m counts\r\n"
    " - z           : zero all accumulators (E1-E12, pulse1-3)\r\n"
    " - ze<n>       : zero individual energy accumulator (n=1-12)\r\n"
    " - zp<n>       : zero individual pulse accumulator (n=1-3)\r\n\r\n";
