/* AUTO GENERATED by scripts/filter.py */

#include <stdint.h>

#define DOWNSAMPLE_TAPS  19u
#define COEFF_UNIQUE_NUM 6u

static const int     downsample_taps             = DOWNSAMPLE_TAPS;
static const int16_t firCoeffs[COEFF_UNIQUE_NUM] = {92,    -279,  957,
                                                    -2670, 10113, 16339};
